# Generated by Django 5.1.4 on 2025-01-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название каталога')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.catalog', verbose_name='Родительский каталог')),
                ('who_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Кто удалил')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название проекта')),
                ('version', models.IntegerField(default=0, verbose_name='Версия')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.catalog', verbose_name='Каталог')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.project', verbose_name='Родительский проект')),
                ('who_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кто удалил')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(max_length=14, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Название инструмента')),
                ('resource', models.IntegerField(verbose_name='Ресурс')),
                ('diameter', models.FloatField(verbose_name='Диаметр (мм)')),
                ('length', models.FloatField(verbose_name='Длина (мм)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='ProjectTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_time', models.IntegerField(verbose_name='Время применения (сек)')),
                ('quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Количество инструментов')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='projects.project')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tool', verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'Инструмент проекта',
                'verbose_name_plural': 'Инструменты проекта',
            },
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['name', 'parent', 'creator'], name='projects_ca_name_a70d49_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['date_delete'], name='projects_ca_date_de_5b7f17_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name', 'catalog', 'parent', 'creator'], name='projects_pr_name_e91c94_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['date_delete'], name='projects_pr_date_de_467a2b_idx'),
        ),
    ]
