# Generated by Django 5.1.4 on 2025-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tool_date_delete_tool_who_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='article',
            field=models.IntegerField(verbose_name='Артикул'),
        ),
    ]
